name: Update Showcase in ReadMe

on:
  workflow_dispatch: # Allows manual trigger

jobs:

  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Print Current Directory
        run: pwd

      - name: List Files
        run: ls -la

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23' # Use your Node.js version

      - name: Install dependencies and run script
        run: |
          npm install
          node update-readme.js

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "your-email@example.com"
          git add README.md
          git commit -m "Update showcase links"
          git push
