name: Update Showcase in ReadMe

on:
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "23" # Use your Node.js version

      - name: Install dependencies and run script
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # Pass the secret here
        run: |
          npm install
          node update-readme.js

      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Stash uncommitted changes (if any)
        run: |
          git stash || echo "No changes to stash"

      - name: Pull latest changes from remote
        run: |
          git fetch origin main
          git rebase origin/main || { echo "Rebase failed. Please resolve conflicts."; exit 1; }

      - name: Check for changes and commit
        run: |
          git add README.md
          git diff --cached --exit-code || git commit -m "Update showcase links"

      - name: Push Changes to Remote
        run: |
          git push origin main || { echo "Failed to push changes. Please resolve conflicts."; exit 1; }
