name: Update Showcase in ReadMe

on:
  workflow_dispatch: # Allows manual trigger


permissions:
  contents: write

jobs:

  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Print Current Directory
        run: pwd

      - name: List Files
        run: ls -la

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23' # Use your Node.js version

      - name: Install dependencies and run script
        run: |
          npm install
          node update-readme.js

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main || echo "No remote changes to pull"
          git add README.md
          git commit -m "Update showcase links" || echo "No changes to commit"
          git push origin main
